postgres:
    build: postgres/
    ports:
    - "5432:5432"

elasticsearch:
    image: elasticsearch

keycloak:
    build: keycloak/
    ports:
    - "8080:8080"
    - "8443:8443"
    links:
    - postgres:postgres
    environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak
    volumes:
    - "./keycloak/standalone-ssl.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml"
    - "./keystore.jks:/opt/jboss/keycloak/standalone/configuration/keystore.jks"
    - "./themes/banana:/opt/jboss/keycloak/standalone/configuration/themes/banana"
#    - "./keycloak/keycloak-server.json:/opt/jboss/keycloak/standalone/configuration/keycloak-server.json"

apiman:
    build: apiman/
    ports:
    - 9080:8080
    - 9443:8443
    - 9990:9990
    links:
    - postgres:postgres
    - elasticsearch:elasticsearch
    volumes:
    - "./apiman/apiman-ds.xml:/opt/jboss/wildfly/standalone/deployments/apiman-ds.xml"
    - "./apiman/apiman.properties:/opt/jboss/wildfly/standalone/configuration/apiman.properties"
    - "./apiman/standalone-apiman.xml:/opt/jboss/wildfly/standalone/configuration/standalone-apiman.xml"
    - "./keystore.jks:/opt/jboss/wildfly/standalone/configuration/keystore.jks"