postgres:
    build: postgres/
    ports:
    - "5432:5432"

elasticsearch:
    image: elasticsearch

keycloak:
    build: keycloak/
    ports:
    - "8080:8080"
    - "8443:8443"
    links:
    - postgres:postgres
    environment:
    - POSTGRES_DATABASE=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak
#    volumes:
#    - "themes/banana:/opt/jboss/keycloak/standalone/configuration/themes/banana"

apiman:
    build: apiman/
    ports:
    - 9080:8080
    - 9443:8443
    - 9990:9990
    links:
    - postgres:postgres
    - elasticsearch:elasticsearch